# Generated by Django 2.2.2 on 2019-09-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='tech',
            field=models.CharField(default='Welll', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='summary',
            name='summary',
            field=models.CharField(max_length=400),
        ),
    ]
